Add skudetails function to get info about sku's from bazaar
cafebazaar/Poolakey pull request #40
Opened 2021-04-20 10:10 UTC by shayanpourvatan

2021-05-01 20:09 UTC, PHELAT approved these changes
LGTM!

2021-05-10 10:32 UTC, hamidrezasahraei requested changes

2021-05-10 10:32 UTC, hamidrezasahraei commented on app/src/main/java/ir/cafebazaar/poolakeysample/MainActivity.kt
> +            if (paymentConnection.getState() == ConnectionState.Connected) {
In order to have better readability, maintainability, and have a smaller method I suggest moving this part to another method and call that method here.
@shayanpourvatan

2021-05-10 10:32 UTC, hamidrezasahraei commented on app/src/main/java/ir/cafebazaar/poolakeysample/MainActivity.kt
> +            if (paymentConnection.getState() == ConnectionState.Connected) {
In order to have better readability, maintainability, and have a smaller method I suggest moving this part to another method and call that method here.
@shayanpourvatan

2021-05-10 10:32 UTC, hamidrezasahraei commented on app/src/main/res/values/strings.xml
> +    <string name="general_get_sku_detail_inapp_text">Get Sku detail of inApp item</string>
We have a typo here, change `inApp` to `in-app`

2021-05-10 10:32 UTC, hamidrezasahraei commented on poolakey/src/main/java/ir/cafebazaar/poolakey/billing/skudetail/GetSkuDetailFunction.kt
> +    override fun function(
Put a blank line here

2021-05-10 10:32 UTC, hamidrezasahraei commented on poolakey/src/main/java/ir/cafebazaar/poolakey/billing/skudetail/GetSkuDetailFunction.kt
> +        try {
This is a veryyyyy long method, Can you break it into smaller units?

2021-05-15 07:13 UTC, merged